### PR TITLE
Add flask template

### PR DESCRIPTION
**Pull request by yashvarshney003**

### CODE REVIEW

**Review by sjchoure — APPROVED** [review]
All good! Ready for merge.

**Comment by yashvarshney003** [comment]
Thank you, sir.

**Comment by saviourcode** [comment]
@yashvarshney003 Hey, are you up for implementing Flask Template once again?

**Comment by yashvarshney003** [comment]
Yes. I will  a make  new PR by Sunday.

**Comment by saviourcode** [comment]
Please be in touch via Slack, will update the further details there

**Comment by yashvarshney003** [comment]
Sorry, sir for not replying. I will DM  you on slack.

**Comment by saviourcode** [comment]
No problem 🙂

**Comment by yashvarshney003** [comment]
Some bug is here trying to solve can't make  now.

**Comment by saviourcode** [comment]
@yashvarshney003 Bug such as? We may help to solve it for now.

**Comment by saviourcode** [comment]
@yashvarshney003 Please close this PR

**Pull request closed without merging**
