### PR TITLE
carousel added on cards

### PR DESCRIPTION
**Pull request by vanshikapandey**

### CODE REVIEW

**Comment by saviourcode** [comment]
@vanshikapandey The Divs were getting overlapped in this version. Can you attach the screenshot of how it was working locally on your machine? P.S. We have reverted the merge of PR #45

**Comment by DARK-art108** [comment]
@vanshikapandey awesome work but do one thing remove the background card provide some more gaps between the cards and do not do overlapping. :)

**Comment by DARK-art108** [comment]
Contact @saviourcode  for further assistance as he has implemented this feature :)

**Comment by DARK-art108** [comment]
> @vanshikapandey The Divs were getting overlapped in this version. Can you attach the screenshot of how it was working locally on your machine? P.S. We have reverted the merge of PR #45

Provide Screenshots for carousal effect

**Comment by saviourcode** [comment]
This how it rendered on the live site.
image

**Comment by vanshikapandey** [comment]
Sir try refreshing it it will automatically be ok , actually it takes few
seconds to be all.set

**Pull request merged**
